apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rta-guard
  labels:
    app: rta-guard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rta-guard
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
