#!/usr/bin/env python3
"""
RTA-GUARD Daily CEO Progress Report

Generates a concise status report from development_progress.json
and sends it to the CEO chat.

Usage: python3 scripts/daily_report.py
"""

import json
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).parent.parent
STATE_FILE = ROOT / "memory" / "development_progress.json"

def load_state():
    with open(STATE_FILE) as f:
        return json.load(f)

def generate_report(state):
    lines = []
    lines.append("📊 **RTA-GUARD Daily CEO Report**")
    lines.append(f"*Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*")
    lines.append("")
    
    # Overall progress
    total_phases = 6
    completed_phases = sum(1 for p in range(1,7) if state[f"phase_{p}"]["status"] == "done")
    lines.append(f"**Progress:** {completed_phases}/{total_phases} phases complete")
    lines.append("")
    
    # Phase-by-phase
    for p in range(1,7):
        phase = state[f"phase_{p}"]
        phase_name = phase.get("name", f"Phase {p}")
        status_icon = "✅" if phase["status"] == "done" else "🟡" if phase["status"] == "in_progress" else "⭕"
        lines.append(f"{status_icon} **{phase_name}**")
        
        # Subphases
        for sub in phase["subphases"]:
            sub_icon = "✅" if sub["done"] else "🟡"
            lines.append(f"  {sub_icon} {sub['name']}")
            if sub.get("notes"):
                lines.append(f"     _{sub['notes']}_")
        lines.append("")
    
    # Blockers
    if state.get("blockers"):
        lines.append("**🚧 Blockers:**")
        for b in state["blockers"]:
            lines.append(f"• Phase {b['phase']}, Subphase {b['subphase']}: {b['issue']}")
        lines.append("")
    
    # Recent history
    if state.get("history"):
        lines.append("**Recent Completions:**")
        for entry in state["history"][-5:]:
            lines.append(f"• {entry['timestamp'][:10]}: {entry['subphase_name']}")
        lines.append("")
    
    # Next up
    lines.append("**Next Focus:**")
    # Find next incomplete subphase
    for p in range(1,7):
        phase = state[f"phase_{p}"]
        for sub in phase["subphases"]:
            if not sub["done"]:
                lines.append(f"Phase {p}: {sub['name']}")
                break
        else:
            continue
        break
    
    lines.append("")
    lines.append("---")
    lines.append("Auto-generated by RTA-GUARD Orchestrator")
    
    return "\n".join(lines)

def main():
    state = load_state()
    report = generate_report(state)
    print(report)
    
    # In a real setup, this would send to Telegram via message tool
    # For now, just output
    print("\n[This report would be sent to CEO chat]")

if __name__ == "__main__":
    main()
